export const TICKS_PER_MILLISECOND = 10_000
export const TICKS_PER_SECOND = TICKS_PER_MILLISECOND * 1_000
export const TICKS_PER_MINUTE = TICKS_PER_SECOND * 60
export const TICKS_PER_HOUR = TICKS_PER_MINUTE * 60
export const TICKS_PER_DAY = TICKS_PER_HOUR * 24
